CREATE table Events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL
)

CREATE table Subscriptions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome TEXT NOT NULL,
  email TEXT NOT NULL,
  link TEXT,
  event_id INTEGER NOT NULL,
  FOREIGN KEY (event_id) REFERENCES Events(id) ON DELETE CASCADE ON UPDATE CASCADE
)

CREATE TABLE Events_link (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event_id INTEGER NOT NULL,
  subscription_id INTEGER NOT NULL,
  link TEXT NOT NULL,
  FOREIGN KEY (event_id) REFERENCES Events(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (subscription_id) REFERENCES Subscriptions(id) ON DELETE CASCADE ON UPDATE CASCADE
)